### PR TITLE
failing tests

### PR DESCRIPTION
**Pull request by babbush**
@idk3 wanted to see the failing tests.

### CODE REVIEW

**Comment by babbush** [comment]
Obviously we don't want this merged (travis should make sure of that though).

**Comment by babbush** [comment]
@idk3  please make a comment here to satisfy the CLA bot.

**Comment by idk3** [comment]
confirming CLA signed

**Comment by idk3** [comment]
Fixed in https://github.com/quantumlib/OpenFermion-ProjectQ/pull/15

**Pull request closed without merging**
